### ISSUE TITLE
one issueeeee

### ISSUE THREAD

**Issue by ghost** [rice-cracker-2234/socket-napse#4]
for some reason i think if roblox lsp or something puts problem next to output it dont execute like this code i put it in synapse and it work i execute in vsc with vs and it didnt work it works with other synapse execute extension tho

getgenv().cool = true 

while cool do 
    print("cool")
    task.wait()
end

**Comment by mikhailramlal** [comment]
> 

nvm now it works but it didnt work before mb

**Comment by rice-cracker-2234** [comment]
lol ok
